
version: '3'

services:
  misc-pywars:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pywars
    ports:
      - "10000:10000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge